[SPARK]
spark.app.name = UserBehaviorStreaming
spark.master = yarn
spark.submit.deployMode = client
spark.driver.host = spark-client
spark.driver.bindAddress = 0.0.0.0

[KAFKA]
KAFKA_BOOTSTRAP_SERVERS = 46.202.167.130:9094,46.202.167.130:9194,46.202.167.130:9294
KAFKA_TOPIC = product_view
KAFKA_SECURITY_PROTOCOL = SASL_PLAINTEXT
KAFKA_SASL_MECHANISM = PLAIN
KAFKA_SASL_JAAS_CONFIG = org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka" password="UnigapKafka@2024";

[POSTGRESQL]
postgres.jdbc.url = jdbc:postgresql://postgres:5432/postgres
postgres.user = postgres
postgres.password = UnigapPostgres@123
postgres.jdbc.driver = org.postgresql.Driver

[STREAMING]
checkpoint.location = file:///tmp/checkpoints/user_behavior
trigger.processing.time = 30 seconds

[IP2LOCATION]
ip2location.path = /spark/data/ip2location/IP-COUNTRY-REGION-CITY.BIN